### ISSUE TITLE
Can't run on gradle 2.14

### ISSUE THREAD

**Issue by nedtwigg** [stempler/bnd-platform#11]
When I run on gradle 2.14, I get the following error:

```
Caused by: java.lang.NoClassDefFoundError: org/eclipse/core/runtime/internal/adaptor/EclipseEnvironmentInfo
        at org.standardout.gradle.plugin.platform.PlatformPlugin$_configureEnvironment_closure9.doCall(PlatformPlugin.groovy:328)
        at org.standardout.gradle.plugin.platform.PlatformPlugin.configureEnvironment(PlatformPlugin.groovy:327)
        at org.standardout.gradle.plugin.platform.PlatformPlugin$configureEnvironment.callCurrent(Unknown Source)
        at org.standardout.gradle.plugin.platform.PlatformPlugin.apply(PlatformPlugin.groovy:67)
        at org.standardout.gradle.plugin.platform.PlatformPlugin.apply(PlatformPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
        at org.gradle.api.Script$apply$2.callCurrent(Unknown Source)
```

**Comment by nedtwigg** [comment]
Sorry, hit send too soon.  I'm cleaning up a PR that will fix this and go into more detail :)

**Comment by stempler** [comment]
@nedtwigg  Your pull request is merged and incorporated in the 1.4.0 release. Can you confirm that it works in Gradle 2.14?

**Comment by nedtwigg** [comment]
Thanks very much Simon!  Been slammed getting slides tied up, but a quick
test shows that the fix is good.  Thanks for quick turnaround :)

On Sunday, June 19, 2016, Simon Templer <notifications@github.com> wrote:

> @nedtwigg <https://github.com/nedtwigg> Your pull request is merged and
> incorporated in the 1.4.0 release. Can you confirm that it works in Gradle
> 2.14?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/stempler/bnd-platform/issues/11#issuecomment-226989189>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACyhwLfcI_qvcufAcwygfiZZRikvGhvlks5qNRRjgaJpZM4I14vE>
> .
>


-- 
Ned Twigg
Lead Software Architect, DiffPlug LLC
540-336-8043
340 S Lemon Ave #3433, Walnut, CA 91789

**Comment by stempler** [comment]
Great. Good luck with your presentation!
