### ISSUE TITLE
NullPointerException during bundle merging

### ISSUE THREAD

**Issue by qqilihq** [stempler/bnd-platform#36]
First of all: bnd-platform looks like THE tool I've been looking for so long. I'm really looking forward to replace our self-built OSGi re-wrapping toolchain, which is a nightmare to maintain. So, thank you very much for making it, it will save lots of my precious time!!

I'm currently trying to create a bundle for Selenium 3.4.0, and because of "split packages" across JARs and all the issues they cause, I want to merge all Selenium JARs into a single one.

Here's my `build.gradle`:

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'org.standardout:bnd-platform:1.5.0'
        }
    }
    
    apply plugin: 'org.standardout.bnd-platform'
    
    repositories {
        jcenter()
    }
    
    platform {
        // def seleniumVersion = '2.53.1' // the older version works
        def seleniumVersion = '3.4.0'
    
        merge(failOnDuplicate: false) {
            match {
                it.group == 'org.seleniumhq.selenium'
            }
            bnd {
                symbolicName = 'org.seleniumhq.selenium.selenium-java-merged'
                bundleName = 'selenium-java-merged'
                version = seleniumVersion
                instruction 'Export-Package', "org.openqa.selenium.*;version=$version"
                instruction 'Private-Package', '*'
            }
        }
    
        bundle("org.seleniumhq.selenium:selenium-java:$seleniumVersion")
    }

This gives me the following NPE:

    $ gradle clean uS --stacktrace
    
    > Task :bundles
    Merging jars selenium-edge-driver-3.4.0.jar,htmlunit-driver-2.26.jar,selenium-firefox-driver-3.4.0.jar,selenium-ie-driver-3.4.0.jar,selenium-java-3.4.0.jar,selenium-remote-driver-3.4.0.jar,selenium-opera-driver-3.4.0.jar,selenium-chrome-driver-3.4.0.jar,selenium-api-3.4.0.jar,selenium-safari-driver-3.4.0.jar,selenium-support-3.4.0.jar - the jars will not be available as separate bundles
    
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':bundles'.
    > java.lang.NullPointerException (no error message)
    
    * Try:
    Run with --info or --debug option to get more log output.
    
    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bundles'.
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
            at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
            at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
            at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
            at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
            at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
            at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
            at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
            at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
            at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
            at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
            at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    Caused by: java.lang.NullPointerException
            at aQute.bnd.osgi.Jar.remove(Jar.java:659)
            at aQute.bnd.osgi.Jar$remove$2.call(Unknown Source)
            at org.standardout.gradle.plugin.platform.internal.util.bnd.BundleHelper.mergeJars(BundleHelper.groovy:281)
            at org.standardout.gradle.plugin.platform.internal.util.bnd.BundleHelper$mergeJars$0.callStatic(Unknown Source)
            at org.standardout.gradle.plugin.platform.internal.util.bnd.BundleHelper.merge(BundleHelper.groovy:239)
            at org.standardout.gradle.plugin.platform.internal.util.bnd.BundleHelper$merge.call(Unknown Source)
            at org.standardout.gradle.plugin.platform.internal.config.Configurations$_createBundles_closure3.doCall(Configurations.groovy:128)
            at org.standardout.gradle.plugin.platform.internal.config.Configurations.createBundles(Configurations.groovy:125)
            at org.standardout.gradle.plugin.platform.internal.config.Configurations$createBundles$1.call(Unknown Source)
            at org.standardout.gradle.plugin.platform.internal.BundlesAction.execute(BundlesAction.groovy:217)
            at org.standardout.gradle.plugin.platform.internal.BundlesAction.execute(BundlesAction.groovy)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
            ... 27 more
    
    
    BUILD FAILED in 2s
    2 actionable tasks: 2 executed

Interesting observation: When building the older version of Selenium 2.53.1, the build works fine. So I'd assume that the issue is caused by some dependency?

**Comment by stempler** [comment]
From the [place where the exception occurs](https://github.com/stempler/bnd-platform/blob/1.5.0/src/main/groovy/org/standardout/gradle/plugin/platform/internal/util/bnd/BundleHelper.groovy#L281) it looks like that the problem could be that there is a Jar that has no Manifest that can be removed. An the bnd Jar class might choke on that and throw the NPE.

Can you verify if there is a Jar included that has no Manifest file (`META-INF/MANIFEST.MF`)?

Solution should be quite easy then, either first checking if the file exists or just ignoring the NPE there.

**Comment by qqilihq** [comment]
Hi Simon,

I've just checked with a more reduced version of my script, which now only uses a subset of the dependency tree for easier debugging:

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'org.standardout:bnd-platform:1.5.0'
        }
    }
    
    apply plugin: 'org.standardout.bnd-platform'
    
    repositories {
        jcenter()
    }
    
    platform {
        def seleniumVersion = '3.4.0'
    
        merge(failOnDuplicate: false) {
            match {
                if (it.group == 'org.seleniumhq.selenium')
                    println "$it.group:$it.name:$it.version --> $it.file"
                it.group == 'org.seleniumhq.selenium'
            }
            bnd {
                symbolicName = 'org.seleniumhq.selenium.selenium-chrome-driver-merged'
                bundleName = 'selenium-chrome-driver-merged'
                version = seleniumVersion
                instruction 'Export-Package', "org.openqa.selenium.*;version=$version"
                instruction 'Private-Package', '*'
            }
        }
    
        bundle("org.seleniumhq.selenium:selenium-chrome-driver:$seleniumVersion")
    }

So the following three files will be merged:

    org.seleniumhq.selenium:selenium-remote-driver:3.4.0 --> /Users/pk/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-remote-driver/3.4.0/2593094fccb4f0317e211674ebfc22fb049c043a/selenium-remote-driver-3.4.0.jar
    org.seleniumhq.selenium:selenium-api:3.4.0 --> /Users/pk/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-api/3.4.0/bf91d238e6eb07f8496ccb61e12e2c868d2bc7e9/selenium-api-3.4.0.jar
    org.seleniumhq.selenium:selenium-chrome-driver:3.4.0 --> /Users/pk/.gradle/caches/modules-2/files-2.1/org.seleniumhq.selenium/selenium-chrome-driver/3.4.0/5a3533c1ec2ba883beb0314dacf7ff932163a4ef/selenium-chrome-driver-3.4.0.jar

I've manually inspected each of the three jar files, and each contains the `MANIFEST.MF`.

**Comment by qqilihq** [comment]
I've done some more debugging, and your original hint about the missing `MANIFEST.MF` was entirely correct. When writing above's post, I did not think about the **source** bundles and only inspected the binary bundles.

I had a look at the source JAR files (e.g. `selenium-remote-driver-3.4.0-sources.jar`), and none of them contains a `MANIFEST.MF`. I'm an entire OSGi dummy, so I have no clue whether that's supposed to be like that or not.

So, the good thing first: Adding the `fetchSources = false` option fixes the exception.

But this way I loose the sources (which ironically was one of the main reasons to switch to bnd-platform in the first place) in conjunction with the bundle merging :-(

Is there any chance to fix this?

**Comment by stempler** [comment]
@qqilihq Thanks for the PR! Nice to see that you find bnd-platform useful.

I think usually there is a manifest also in source Jars, when they are built with Maven or Gradle. So this never occurred (at least to me) before.

I built the current state and published the SNAPSHOT. See [here](https://github.com/stempler/bnd-platform#using-the-current-snapshot) on how to use the current SNAPSHOT version.
